Repository AlexLarusso/ui-internship-lwo3-angular-team, pull requests merged in 2019-10, with the labels that each got.

#6 [FEATURE: UIPT-25] - Carousel
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/main/main.component.html
  src/app/product-short-info.service.ts
  src/app/shared/product-carousel/product-carousel.component.html
  src/app/shared/product-carousel/product-carousel.component.scss
  src/app/shared/product-carousel/product-carousel.component.spec.ts
  src/app/shared/product-carousel/product-carousel.component.ts
Labels: FINAL_REVIEW_NEEDED

#8 [FIX]: App spec
  src/app/app.component.spec.ts
Labels: CODE_REVIEW_NEEDED

#3 [FEATURE: UIPT-32] - Scroll
  angular.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/main/main.component.html
  src/app/main/main.component.ts
  src/app/scroll-anchor.directive.ts
  src/app/scroll.service.spec.ts
  src/app/scroll.service.ts
  src/app/scroll/scroll.component.html
  src/app/scroll/scroll.component.scss
  src/app/scroll/scroll.component.spec.ts
  src/app/scroll/scroll.component.ts
Labels: FINAL_REVIEW_NEEDED

#4 [FEATURE: UIPT-19] - Slideshow
  README.md
  angular.json
  package.json
  src/app/app.module.ts
  src/app/header/promo/promo.component.html
  src/app/header/promo/promo.component.scss
  src/app/slideshow/slideshow.animations.ts
  src/app/slideshow/slideshow.component.html
  src/app/slideshow/slideshow.component.scss
  src/app/slideshow/slideshow.component.spec.ts
  src/app/slideshow/slideshow.component.ts
Labels: FINAL_REVIEW_NEEDED

#9 [FEATURE: UIPT-34] - Spinner
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/loader.interceptor.ts
  src/app/loader.service.ts
  src/app/shared/loader/loader.component.html
  src/app/shared/loader/loader.component.scss
  src/app/shared/loader/loader.component.spec.ts
  src/app/shared/loader/loader.component.ts
  src/app/shared/product-carousel/product-carousel.component.ts
  src/styles.scss
Labels: FINAL_REVIEW_NEEDED

#2 [FEATURE: UIPT-22] - Join us
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/join-us/join-us.html
  src/app/join-us/join-us.scss
  src/app/join-us/join-us.spec.ts
  src/app/join-us/join-us.ts
  src/app/local-storage.service.spec.ts
  src/app/local-storage.service.ts
  src/app/shared/button/button.component.html
  src/app/shared/button/button.component.scss
  src/app/shared/button/button.component.ts
  src/app/styles/_variables.scss
Labels: FINAL_REVIEW_NEEDED

#5 [FEATURE: UIPT-5] - Application router
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/header/category-menu/category-menu.component.html
  src/app/header/header.component.html
  src/app/http.service.ts
  src/app/main/main.component.ts
  src/app/pages/home/home.component.ts
  src/app/pages/home/home.html
  src/app/pages/not-found/not-found.component.ts
  src/app/pages/not-found/not-found.html
  src/app/pages/not-found/not-found.scss
  src/app/pages/product-details-page/product-details-page.component.ts
  src/app/pages/product-details-page/product-details-page.html
  src/app/pages/product-list-page/product-list-page.component.ts
  src/app/pages/product-list-page/product-list-page.html
  src/app/product-details/product-details.component.html
  src/app/product-details/product-details.component.scss
  src/app/product-details/product-details.component.spec.ts
  src/app/product-details/product-details.component.ts
  src/app/product-list/product-list.component.html
  src/app/product-short-info.service.ts
  src/app/product-short-info.ts
  src/app/product.resolver.ts
  src/app/product.service.ts
  src/app/product.ts
  src/app/promo/promo.component.html
  src/app/promo/promo.component.scss
  src/app/promo/promo.component.ts
  src/app/scroll-anchor.directive.ts
  src/app/scroll.service.spec.ts
  src/app/scroll.service.ts
  src/app/scroll/scroll.component.html
  src/app/scroll/scroll.component.spec.ts
  src/app/scroll/scroll.component.ts
  src/app/shared/main-logo/main-logo.component.html
  src/app/shared/product-item/product-item.component.html
  src/app/shared/product-item/product-item.component.ts
  src/assets/server-data/data.json
Labels: FINAL_REVIEW_NEEDED

#10 [FIX: UIPT-19] - Slideshow
  src/app/slideshow/slideshow.component.scss
  src/app/slideshow/slideshow.component.ts
Labels: FINAL_REVIEW_NEEDED

#13 [FIX: UIPT-32] - Scroll
  src/app/app.component.ts
  src/app/app.html
  src/app/components/scroll/scroll.component.ts
  src/app/components/scroll/scroll.html
  src/app/components/scroll/scroll.scss
  src/app/pages/home/home.html
  src/app/shared/product-carousel/product-carousel.html
  src/app/shared/services/scroll.service.ts
  src/app/styles/_variables.scss
Labels: FIXES_NEEDED

#14 [REFACTORING] - TODO fixes
  src/app/app.component.ts
  src/app/app.enum.ts
  src/app/components/join-us/join-us.component.ts
  src/app/components/join-us/join-us.html
  src/app/components/parallax/parallax.scss
  src/app/components/promo/promo.html
  src/app/components/promo/promo.scss
  src/app/components/scroll/scroll.component.ts
  src/app/components/scroll/scroll.scss
  src/app/components/slideshow/slideshow.component.ts
  src/app/components/slideshow/slideshow.scss
  src/app/components/story/story.html
  src/app/interfaces/product-short-info.interface.ts
  src/app/pages/home/home.component.ts
  src/app/pages/not-found/not-found.html
  src/app/pages/not-found/not-found.module.ts
  src/app/pages/not-found/not-found.scss
  src/app/pages/product-details-page/product-details-page.html
  src/app/pages/product-details-page/product-details-page.module.ts
  src/app/pages/product-list-page/product-list-page.component.ts
  src/app/pages/product-list-page/product-list-page.html
  src/app/shared/button/button.scss
  src/app/shared/footer/footer.html
  src/app/shared/footer/footer.scss
  src/app/shared/header/category-menu/category-menu.html
  src/app/shared/header/category-menu/category-menu.scss
  src/app/shared/header/header.html
  src/app/shared/header/line-bar/line-bar.scss
  src/app/shared/header/main-menu/main-menu.scss
  src/app/shared/loader/loader.component.ts
  src/app/shared/loader/loader.html
  src/app/shared/loader/loader.scss
  src/app/shared/main-logo/main-logo.html
  src/app/shared/popular-list/popular-list.component.ts
  src/app/shared/product-carousel/product-carousel.component.ts
  src/app/shared/product-carousel/product-carousel.html
  src/app/shared/product-carousel/product-carousel.scss
  src/app/shared/product-details/product-details.component.ts
  src/app/shared/product-details/product-details.html
  src/app/shared/product-item/product-item.component.ts
  src/app/shared/product-item/product-item.html
  src/app/shared/product-item/product-item.scss
  src/app/shared/product-list/product-list.component.ts
  src/app/shared/product-list/product-list.html
  src/app/shared/sale-banner/sale-banner.scss
  src/app/shared/services/product-short-info.service.ts
  src/app/shared/services/product.resolver.ts
  src/app/shared/services/scroll.service.ts
Labels: FINAL_REVIEW_NEEDED

#15 [FEATURE: UIPT-24] - Similar products
  src/app/components/similar-products/similar-products.component.ts
  src/app/components/similar-products/similar-products.html
  src/app/pages/product-details-page/product-details-page.module.ts
  src/app/shared/product-carousel/product-carousel.component.ts
  src/app/shared/product-carousel/product-carousel.html
  src/app/shared/product-details/product-details.component.ts
  src/app/shared/product-details/product-details.html
  src/app/shared/product-list/product-list.html
  src/app/shared/services/product-filter.service.ts
  src/app/shared/services/product-short-info.service.ts
  src/app/shared/services/product.resolver.ts
  src/app/shared/services/product.service.ts
  src/app/shared/shared.module.ts
Labels: FINAL_REVIEW_NEEDED

#18 [FEATURE: UIPT-37] - NgRx Store
  src/app/app.html
  src/app/app.module.ts
  src/app/components/counter/counter.component.ts
  src/app/components/counter/counter.html
  src/app/components/counter/counter.scss
  src/app/shared/loader/loader.component.ts
  src/app/shared/loader/loader.html
  src/app/shared/services/loader.interceptor.ts
  src/app/shared/services/loader.service.ts
  src/app/store/actions/counter.actions.ts
  src/app/store/actions/loader.actions.ts
  src/app/store/app.store.ts
  src/app/store/reducers/counter.reducer.ts
  src/app/store/reducers/loader.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/app/store/selectors/counter.selectors.ts
  src/app/store/selectors/loader.selectors.ts
Labels: FINAL_REVIEW_NEEDED

#19 [FEATURE: UIPT-26] - Product order: Product details
  src/app/app.component.ts
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-details/product-details.html
  src/app/components/product-details/product-details.scss
  src/app/components/product-order/product-order.component.ts
  src/app/components/product-order/product-order.html
  src/app/components/product-order/product-order.scss
  src/app/components/product-preview/product-preview.component.ts
  src/app/components/product-preview/product-preview.html
  src/app/components/product-preview/product-preview.scss
  src/app/interfaces/product-description.interface.ts
  src/app/interfaces/product-details.interface.ts
  src/app/interfaces/product-options.interface.ts
  src/app/pages/product-details-page/product-details-page.component.ts
  src/app/pages/product-details-page/product-details-page.html
  src/app/pages/product-details-page/product-details-page.module.ts
  src/app/shared/accordeon/accordeon.component.ts
  src/app/shared/accordeon/accordeon.html
  src/app/shared/accordeon/accordeon.scss
  src/app/shared/button/button.scss
  src/app/shared/dropdown/dropdown-component.ts
  src/app/shared/dropdown/dropdown.html
  src/app/shared/dropdown/dropdown.scss
  src/app/shared/product-details/product-details.component.ts
  src/app/shared/product-details/product-details.html
  src/app/shared/select-color/select-color.component.ts
  src/app/shared/select-color/select-color.html
  src/app/shared/select-color/select-color.scss
  src/app/shared/select-number/select-number.component.ts
  src/app/shared/select-number/select-number.html
  src/app/shared/select-number/select-number.scss
  src/app/shared/services/product.service.ts
  src/app/shared/shared.module.ts
  src/assets/server-data/data.json
  tsconfig.json
Labels: CODE_REVIEW_NEEDED

#20 [REFACTORING] - Services, Similar Products, Carousel
  src/app/app.component.ts
  src/app/app.enum.ts
  src/app/app.module.ts
  src/app/components/counter/counter.component.ts
  src/app/components/join-us/join-us.component.ts
  src/app/components/scroll/scroll.component.ts
  src/app/components/similar-products/similar-products.component.ts
  src/app/components/similar-products/similar-products.html
  src/app/components/slideshow/slideshow.animations.ts
  src/app/components/slideshow/slideshow.component.ts
  src/app/interfaces/index.ts
  src/app/interfaces/page-anchor.interface.ts
  src/app/interfaces/product-short-info.interface.ts
  src/app/interfaces/product-similar-options.interface.ts
  src/app/interfaces/product.interface.ts
  src/app/pages/home/home.component.ts
  src/app/pages/home/home.html
  src/app/pages/home/home.module.ts
  src/app/pages/product-details-page/product-details-page.component.ts
  src/app/pages/product-details-page/product-details-page.html
  src/app/pages/product-details-page/product-details-page.module.ts
  src/app/pages/product-list-page/product-list-page.component.ts
  src/app/pages/product-list-page/product-list-page.module.ts
  src/app/shared/directives/index.ts
  src/app/shared/header/line-bar/line-bar.component.ts
  src/app/shared/header/main-menu/main-menu.component.ts
  src/app/shared/loader/loader.component.ts
  src/app/shared/popular-list/popular-list.component.ts
  src/app/shared/product-carousel/product-carousel.component.ts
  src/app/shared/product-item/product-item.component.ts
  src/app/shared/product-list/product-list.component.ts
  src/app/shared/sale-banner/sale-banner.component.ts
  src/app/shared/services/http.service.ts
  src/app/shared/services/index.ts
  src/app/shared/services/loader.interceptor.ts
  src/app/shared/services/product-filter.service.ts
  src/app/shared/services/product-short-info.service.ts
  src/app/shared/services/product.resolver.ts
  src/app/shared/services/product.service.ts
  src/app/shared/services/scroll.service.ts
  src/app/shared/shared.module.ts
  src/app/store/app.store.ts
  src/app/store/reducers/counter.reducer.ts
  src/app/store/reducers/loader.reducer.ts
  src/assets/server-data/data.json
Labels: CODE_REVIEW_NEEDED, FINAL_REVIEW_NEEDED

#22 [FIX]-Eslint and rest errors corrections
  src/app/components/join-us/join-us.html
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-order/product-order.component.ts
  src/app/components/product-order/product-order.html
  src/app/components/product-preview/product-preview.component.ts
  src/app/components/product-preview/product-preview.html
  src/app/components/similar-products/similar-products.component.ts
  src/app/interfaces/index.ts
  src/app/interfaces/page-anchor.interface.ts
  src/app/interfaces/product-description.interface.ts
  src/app/interfaces/product-details.interface.ts
  src/app/interfaces/product-options.interface.ts
  src/app/interfaces/product-similar-options.interface.ts
  src/app/pages/home/home.component.ts
  src/app/pages/product-details-page/product-details-page.component.ts
  src/app/shared/accordeon/accordeon.component.ts
  src/app/shared/directives/index.ts
  src/app/shared/dropdown/dropdown-component.ts
  src/app/shared/select-color/select-color.component.ts
  src/app/shared/select-color/select-color.scss
  src/app/shared/select-number/select-number.component.ts
  src/app/shared/services/index.ts
  src/app/shared/services/product.service.ts
Labels: CODE_REVIEW_NEEDED

#24 [FEATURE] - NGRX-Devtools
  package-lock.json
  package.json
  src/app/app.module.ts
Labels: CODE_REVIEW_NEEDED

#25 [FIX]: Web storage
  src/app/components/join-us/join-us.component.ts
  src/app/shared/services/web-storage/local-storage.service.ts
  src/app/shared/services/web-storage/session-storage.service.ts
  src/app/shared/services/web-storage/web-storage.service.ts
  src/app/store/actions/web-storage.actions.ts
  src/app/store/app.store.ts
  src/app/store/reducers/web-storage.reducer.ts
  src/app/store/selectors/web-storage.selectors.ts
Labels: CODE_REVIEW_NEEDED

#23 [FEATURE: UIPT-30] - Wish list page
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/product-order/product-order.component.ts
  src/app/components/product-order/product-order.html
  src/app/components/wish-list/wish-list.component.ts
  src/app/components/wish-list/wish-list.html
  src/app/components/wish-list/wish-list.scss
  src/app/interfaces/product-details.interface.ts
  src/app/pages/wish-list-page/wish-list-page.component.ts
  src/app/pages/wish-list-page/wish-list-page.html
  src/app/pages/wish-list-page/wish-list-page.module.ts
  src/app/shared/header/main-menu/main-menu.component.ts
  src/app/shared/header/main-menu/main-menu.html
  src/app/shared/header/main-menu/main-menu.scss
  src/app/shared/product-item/product-item.component.ts
  src/app/shared/product-item/product-item.html
  src/app/shared/product-item/product-item.scss
  src/app/shared/shared.module.ts
  src/app/shared/wish-button/wish-button.component.ts
  src/app/shared/wish-button/wish-button.html
  src/app/shared/wish-button/wish-button.scss
  src/app/store/actions/wish-list.actions.ts
  src/app/store/app.store.ts
  src/app/store/reducers/wish-list.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/app/store/selectors/wish-list.selectors.ts
Labels: FINAL_REVIEW_NEEDED

#27 [FEATURE] - PDP store integration
  src/app/components/product-details/product-details.scss
  src/app/components/product-order/product-order.component.ts
  src/app/components/product-order/product-order.html
  src/app/components/product-preview/product-preview.component.ts
  src/app/components/product-preview/product-preview.html
  src/app/interfaces/product-image.interface.ts
  src/app/interfaces/product-options.interface.ts
  src/app/interfaces/product.interface.ts
  src/app/shared/select-color/select-color.component.ts
  src/app/shared/select-color/select-color.html
  src/app/shared/select-color/select-color.scss
  src/app/shared/select-number/select-number.component.ts
  src/app/shared/select-number/select-number.html
  src/app/shared/select-size/select-size.component.ts
  src/app/shared/select-size/select-size.html
  src/app/shared/select-size/select-size.scss
  src/app/shared/shared.module.ts
  src/app/store/actions/product-options.actions.ts
  src/app/store/app.store.ts
  src/app/store/reducers/product-options.reducer.ts
  src/app/store/reducers/web-storage.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/app/store/selectors/loader.selectors.ts
  src/app/store/selectors/product-options.selector.ts
  src/app/store/selectors/web-storage.selectors.ts
  src/assets/server-data/data.json
Labels: FINAL_REVIEW_NEEDED

#28 [FEATURE: UIPT-17] - Popular products
  src/app/interfaces/product-short-info.interface.ts
  src/app/interfaces/product.interface.ts
  src/app/shared/popular-list/popular-list.component.ts
  src/app/shared/popular-list/popular-list.html
  src/app/shared/product-carousel/product-carousel.html
  src/app/shared/product-item/product-item.component.ts
  src/app/shared/product-item/product-item.html
  src/app/shared/product-item/product-item.scss
  src/app/shared/product-list/product-list.html
  src/app/shared/services/product.service.ts
  src/app/styles/_variables.scss
  src/assets/server-data/data.json
Labels: FINAL_REVIEW_NEEDED

#29 [FEATURE: UIPT-?] - Load More
  src/app/app.module.ts
  src/app/shared/button/button.scss
  src/app/shared/product-list/product-list.component.ts
  src/app/shared/product-list/product-list.html
  src/app/shared/product-list/product-list.scss
  src/app/store/actions/products.action.ts
  src/app/store/app.store.ts
  src/app/store/effects/products.effects.ts
  src/app/store/reducers/products.reducer.ts
  src/app/store/reducers/web-storage.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/app/store/selectors/products.selectors.ts
Labels: FINAL_REVIEW_NEEDED

#30 [FEATURE] - Error Handler, Notification service
  src/app/app.enum.ts
  src/app/app.html
  src/app/app.module.ts
  src/app/components/notification/notification.component.ts
  src/app/components/notification/notification.html
  src/app/components/notification/notification.scss
  src/app/components/product-order/product-order.component.ts
  src/app/components/wish-list/wish-list.component.ts
  src/app/components/wish-list/wish-list.html
  src/app/components/wish-list/wish-list.scss
  src/app/interfaces/index.ts
  src/app/interfaces/notification.interface.ts
  src/app/pages/error-sample/error-sample.component.ts
  src/app/pages/error-sample/error-sample.html
  src/app/pages/error-sample/error-sample.module.ts
  src/app/pages/error-sample/error-sample.scss
  src/app/pages/product-details-page/product-details-page.component.ts
  src/app/pages/product-details-page/product-details-page.html
  src/app/pages/product-details-page/product-details-page.scss
  src/app/shared/services/errors.handler.ts
  src/app/shared/services/http.service.ts
  src/app/shared/services/notification.service.ts
Labels: CODE_REVIEW_NEEDED

#32 [FIX] - Errors and css style issues
  src/app/components/join-us/join-us.scss
  src/app/components/notification/notification.scss
  src/app/components/parallax/parallax.component.ts
  src/app/components/parallax/parallax.html
  src/app/components/parallax/parallax.scss
  src/app/components/product-order/product-order.component.ts
  src/app/components/wish-list/wish-list.scss
  src/app/pages/error-sample/error-sample.html
  src/app/pages/wish-list-page/wish-list-page.html
  src/app/shared/popular-list/popular-list.scss
  src/app/shared/product-item/product-item.html
  src/app/shared/product-item/product-item.scss
  src/app/shared/product-list/product-list.scss
  src/app/shared/sale-banner/sale-banner.scss
  src/app/shared/select-number/select-number.scss
  src/app/shared/services/http.service.ts
  src/app/shared/services/loader.interceptor.ts
  src/app/shared/shared.module.ts
  src/assets/img/fall_fashion.jpg
  src/assets/img/shopping.jpg
  src/assets/img/spring_fashion.jpg
  src/assets/img/summer_fashion.jpg
  src/assets/img/winter_fashion.png
Labels: CODE_REVIEW_NEEDED

#33 [FIX] - DIST path
  angular.json
Labels: CODE_REVIEW_NEEDED

#37 [FIX] - Scroll Feature
  src/app/app.component.ts
  src/app/app.html
  src/app/components/recently-viewed/recently-viewed.html
  src/app/components/scroll/scroll.html
  src/app/interfaces/page-anchor.interface.ts
  src/app/pages/home/home.component.ts
  src/app/pages/home/home.html
  src/app/pages/home/home.module.ts
  src/app/pages/product-list-page/product-list-page.component.ts
  src/app/pages/product-list-page/product-list-page.html
  src/app/pages/wish-list-page/wish-list-page.component.ts
  src/app/pages/wish-list-page/wish-list-page.html
  src/app/shared/directives/scroll-anchor.directive.ts
  src/app/shared/dropdown/dropdown-component.ts
  src/app/shared/services/scroll.service.ts
  src/app/shared/shared.module.ts
Labels: CODE_REVIEW_NEEDED

#38 [FIX] - Predemo hotfix
  src/app/app.module.ts
  src/app/components/notification/notification.html
  src/app/components/notification/notification.scss
  src/app/pages/error-page/error-page.component.ts
  src/app/pages/error-page/error-page.html
  src/app/pages/error-page/error-page.module.ts
  src/app/pages/error-page/error-page.scss
  src/app/pages/error-sample/error-sample.component.ts
  src/app/pages/error-sample/error-sample.html
  src/app/pages/error-sample/error-sample.scss
  src/app/shared/directives/index.ts
  src/app/shared/directives/modal-open.directive.ts
  src/app/shared/loader/loader.html
  src/app/shared/product-item/product-item.scss
  src/app/shared/services/errors.handler.ts
  src/app/shared/services/http.service.ts
  src/app/shared/shared.module.ts
  src/app/styles/_common.scss
  src/assets/img/spring_fashion.jpg
Labels: FIXES_NEEDED

#39 [FIX-2] Loader fixed
  src/app/shared/loader/loader.html
Labels: CODE_REVIEW_NEEDED
